spring.application.name=projeto1

# Configuração do H2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dbapp
# ou spring.datasource.url=jdbc:file:./data para direcionar a um arquivo local.
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=nome
spring.datasource.password=senha

# Configuração do JPA
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.dll-auto=update
# ATENÇÃO: A apresentação de dados no SQL só é viável para ambiente de desenvolvimento e testes. Não é seguro disponibilizar a visualização para projetos reais.
spring.jpa.show-sql=true